[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python api.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
source = "."

[services.variables]
PORT = "8000"
FLASK_ENV = "production"
